Keystone user issues on Puppet Enterprise.
Puppet Enterprise doesn't work for:
 - keystone_user;
 - keystone_tenant;
 - keystone_user_role;

    Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not autoload puppet/type/keystone_user: Malformed version number string 3.8.1 (Puppet Enterprise 3.8.1)

This is due to the modified version string that Puppet Enterprise uses.
This patch takes this string into consideration.  It has been tested
successfully on Puppet Enterprise.

Change-Id: I8c79b9331134762620509ca0a6c09e16e534ad9b
Closes-Bug: #1516687