Require json to prevent missing method error
Using this type evaluated to the following error message:

```
Error: /Stage[main]/Keystone::Roles::Admin/Keystone_user[admin]: Could not evaluate: undefined method `to_json' for #<Hash:0x00000004e2d458>
```a